name: CD

on:
  push:
    branches:
      - ops/cd
      - main
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: "famcan-riskassessment"
          password: ${{ secrets.PAT }}

      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker compose push

      - name: Copy configuration files
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "docker-compose.yml"
          target: "/root/frontend"

      - name: Deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /root/frontend
            docker compose down
            sleep 10
            docker compose pull
            docker compose up -d
